dataset: "/media/lang/Elements/KAIST/urban08"
save_to: "/media/lang/Elements/KAIST/urban08/test_bag"

altimeter: true
altimeter_topic: "/altimeter_data"

encoder: true
encoder_irp_topic: "/encoder_count"
encoder_raw_topic: "/velocity"

fog: true
fog_topic: "/dsp1760_data"

gps: true
gps_topic: "/gps/fix"

vrs: true
vrs_topic: "/vrs_gps_data"

imu: true
imu_irp_topic: "/xsens_imu_data"
imu_raw_topic: "/imu/data_raw"
imu_mag_topic: "/imu/mag"

velodyne: true
velodyne_left_topic: "/velodyne_points"
velodyne_right_topic: "/velodyne_points"

sick: false
sick_back_topic: "/lms511_back/scan"
sick_middle_topic: "/lms511_middle/scan"

stereo: false
stereo_left_topic: "/stereo/left/image_raw"
stereo_right_topic: "/stereo/right/image_raw"
